version: '3'

networks:
  oracle_oraclenet:
    external: true

services:
  craftgame_jupyter:
    build: ../
    image: craftgame_jupyter
    container_name: oraclenet-craftgame-container
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 2048M
    restart: always
    env_file:
      - ./.env
    networks:
      - oracle_oraclenet
    volumes:
      - ../notebook:/home/jovyan/notebook
    user: root
    environment:
        GRANT_SUDO: "yes"
